stages:          # List of stages for jobs, and their order of execution
  - deploy


deploy-job:      # This job runs in the deploy stage.
  stage: deploy
  script:
    - echo "Deploying application..."
    - cd /home/debian/ecoTracker/datamanager/
    - git pull
    - echo "Application successfully deployed."
    - docker logout
